FRAGEN = [
    {"level":1,"kategorie":"Allgemeinwissen","frage":"Welches Land hat die längste Küstenlinie der Welt?",
     "antworten":{"A":"Russland","B":"Kanada","C":"Norwegen","D":"Australien"},"richtig":"B"},
    {"level":2,"kategorie":"Allgemeinwissen","frage":"Was ist das schwerste natürlich vorkommende Element?",
     "antworten":{"A":"Uran","B":"Blei","C":"Osmium","D":"Plutonium"},"richtig":"C"},
    {"level":3,"kategorie":"Allgemeinwissen","frage":"Wie viele Knochen hat ein erwachsener Mensch?",
     "antworten":{"A":"196","B":"206","C":"216","D":"226"},"richtig":"B"},
    {"level":4,"kategorie":"Allgemeinwissen","frage":"Welches Tier hat das größte Herz?",
     "antworten":{"A":"Elefant","B":"Blauwal","C":"Nilpferd","D":"Giraffe"},"richtig":"B"},
    {"level":5,"kategorie":"Allgemeinwissen","frage":"In welchem Land liegt der Kilimandscharo?",
     "antworten":{"A":"Kenia","B":"Uganda","C":"Tansania","D":"Äthiopien"},"richtig":"C"},
    {"level":6,"kategorie":"Logik & Zahlenfolgen",
     "frage":"Welche Zahl fehlt?\n5 — 10 — 20 — 40 — ?",
     "antworten":{"A":"60","B":"70","C":"80","D":"90"},"richtig":"C",
     "seq":"5  —  10  —  20  —  40  —  ?"},
    {"level":7,"kategorie":"Logik & Zahlenfolgen",
     "frage":"Fibonacci-Folge – was kommt als nächstes?\n1 — 1 — 2 — 3 — 5 — 8 — ?",
     "antworten":{"A":"11","B":"12","C":"13","D":"14"},"richtig":"C",
     "seq":"1  1  2  3  5  8  ?"},
    {"level":8,"kategorie":"Logik & Zahlenfolgen",
     "frage":"Welche Zahl fehlt?\n81 — 27 — 9 — 3 — ?",
     "antworten":{"A":"0","B":"1","C":"2","D":"3"},"richtig":"B",
     "seq":"81  —  27  —  9  —  3  —  ?"},
    {"level":9,"kategorie":"Logik & Zahlenfolgen",
     "frage":"Welche Zahl kommt als nächstes?\n2 — 5 — 10 — 17 — 26 — ?",
     "antworten":{"A":"33","B":"35","C":"37","D":"39"},"richtig":"C",
     "seq":"2  5  10  17  26  ?"},
    {"level":10,"kategorie":"Logik & Zahlenfolgen",
     "frage":"Wenn A=1, B=2, C=3 …\nWas ergibt D + F + H?",
     "antworten":{"A":"18","B":"20","C":"22","D":"24"},"richtig":"A",
     "seq":"D = 4   F = 6   H = 8"},
    {"level":11,"kategorie":"Konzentration",
     "frage":"Wie viele gerade Zahlen liegen zwischen 14 und 26?",
     "antworten":{"A":"4","B":"5","C":"6","D":"7"},"richtig":"C"},
    {"level":12,"kategorie":"Konzentration",
     "frage":"Ein Zug fährt 90 km/h.\nWie weit kommt er in 40 Minuten?",
     "antworten":{"A":"50 km","B":"55 km","C":"60 km","D":"65 km"},"richtig":"C"},
    {"level":13,"kategorie":"Konzentration",
     "frage":"Wie viele Buchstaben 'S' enthält der Satz?",
     "antworten":{"A":"5","B":"6","C":"7","D":"8"},"richtig":"C",
     "seq":"Sechs Schüsse schoss der Schütz"},
    {"level":14,"kategorie":"Konzentration",
     "frage":"15 × 4 − 18 ÷ 3 = ?",
     "antworten":{"A":"52","B":"54","C":"56","D":"58"},"richtig":"B",
     "seq":"15 × 4  −  18 ÷ 3  =  ?"},
    {"level":15,"kategorie":"Konzentration",
     "frage":"Umfang eines Quadrats mit Seite 7 cm?",
     "antworten":{"A":"21 cm","B":"28 cm","C":"35 cm","D":"49 cm"},"richtig":"B"},
]

IQ_TABELLE = {
    0:85, 1:88, 2:91, 3:94, 4:97,
    5:100, 6:103, 7:106, 8:109, 9:112,
    10:116, 11:120, 12:125, 13:130, 14:138, 15:145,
}

IQ_BEZEICHNUNG = {
    range(0,   86): "Unterdurchschnittlich",
    range(86,  95): "Leicht unterdurchschnittlich",
    range(95, 105): "Durchschnittlich",
    range(105,115): "Überdurchschnittlich",
    range(115,125): "Intelligent",
    range(125,135): "Hochbegabt",
    range(135,200): "Ausnahmetalent / Genie",
}

PREISSTUFEN = {
    1:"100 €", 2:"200 €", 3:"300 €", 4:"500 €",
    5:"1.000 €", 6:"2.000 €", 7:"4.000 €", 8:"8.000 €",
    9:"16.000 €", 10:"32.000 €", 11:"64.000 €", 12:"125.000 €",
    13:"250.000 €", 14:"500.000 €", 15:"1.000.000 €",
}

SICHERHEITSSTUFEN = [5, 10]
